name: build
on: [push]
jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          # ghc-version: '8.10.7' # Exact version of ghc to use
          enable-stack: true
          stack-no-global: true
          stack-setup-ghc: true
          stack-version: 'latest'
      - run: stack --no-nix build
